version: 0.2

phases:
  install:
    commands:
     # variables
      - REPOSITORY_URI=536771765020.dkr.ecr.us-east-1.amazonaws.com/log4japp
      - ARTIFACT=log4j-rest
      - ARTIFACT_TYPE=.jar 
      - TAG_NAME=$REPOSITORY_URI:latest
      - echo $AWS_DEFAULT_REGION 
      - echo $ARTIFACT
      - echo $ARTIFACT_TYPE
      - echo $REPOSITORY_URI
      - echo $TAG_NAME  
      # installation
      - sudo yum update -y
      - yum install -y maven
      # Amazon Linux 2
      #- sudo amazon-linux-extras install java-openjdk11
      #- sudo yum install -y docker
      #- sudo systemctl start docker.service
      #- apt-get install -y gradle

  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - mvn package
      #- echo Gradle Build
      #- chmod +x gradlew
      #- ./gradlew build
      #- gradle build 
      
      - echo Building the Docker image...  
      - sudo docker build -t $TAG_NAME .
      - docker tag $TAG_NAME $TAG_NAME
  post_build:
    commands:
      #- docker tag $REPOSITORY_URI:$ARTIFACT $REPOSITORY_URI:$$ARTIFACT
       - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 536771765020.dkr.ecr.us-east-1.amazonaws.com) 
       - echo Build completed on 'date'
       - echo Pushing the Docker images...
       - docker push $TAG_NAME
       #- aws ecs list-services --cluster UngerwECS
       #- aws ecs update-service --cluster UngerwECS --service SpringBootService-Service-XBO2INJQRTEO --task-definition UngerwSpringBootTD
       
artifacts:
     files:
      - imagedefinitions.json  
      - target/log4j-rest-1.0.jar
